# docker build -t edge_inference -f Dockerfile.dev-tx2-4.3_b132-py3 .
# docker run --privileged -it --name edge_inference --network footprints -v /WildAI:/WildAI -v /w251-WildTrackAI/edgeInference:/app -w /app edge_inference

FROM w251/tensorrt:dev-tx2-4.3_b132

RUN apt update && apt install -y python3-pip
RUN apt install -y libhdf5-serial-dev hdf5-tools libhdf5-dev zlib1g-dev zip libjpeg8-dev
RUN apt-get install -y mosquitto-clients

RUN pip3 install -U numpy==1.16.1 future==0.17.1 mock==3.0.5 h5py==2.9.0 keras_preprocessing==1.0.5 keras_applications==1.0.8 gast==0.2.2 enum34 futures protobuf
RUN pip3 install -U pip
RUN pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v43 tensorflow-gpu
RUN pip3 install pillow
RUN pip3 install paho-mqtt

